# Generated by Django 5.0.3 on 2024-03-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phoneNo1', models.CharField(max_length=10)),
                ('phoneNo2', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
